name: app_p_79
description: A new Flutter project.
version: 1.0.0
environment: 
  sdk: '>=3.2.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  mirai_dropdown_menu: 0.0.7+3
  shared_preferences: ^2.2.2
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  toggle_switch: ^2.1.0
  connectivity_plus: ^5.0.2
  app_settings: ^5.1.1
  share_plus: ^7.0.2
  url_launcher: ^6.2.2
  image_picker: ^0.8.9
  onesignal_flutter: 3.5.1
  layout_manager:
    git:
      url: https://github.com/ArturKozack/layoutManager.git
      ref: no_onesignal
  flutter_image_compress: ^2.3.0
  flutter_svg_provider: ^1.0.3


dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
